### ISSUE TITLE
Relayers use latest as default option

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-relayer#142]
To avoid spamming RPC endpoints accidentally, we should set indexing from the latest block as a default behavior if no start block is set.

**Comment by mpetrun5** [comment]
Not sure if this should be default. As for most production use relayers it shouldn't be default.

**Comment by P1sar** [comment]
@mpetrun5 Why? I imagine that for most of the cases when partners lunch relayers they just need to pars from latest block by default (if there is no anything on block store ofcs)

**Comment by mpetrun5** [comment]
For most cases (when restarting relayers) it should just use the block from blockstore to prevent skipping blocks.
The latest flag is an exception just when first starting relayers to store the latest blocks. Everything after that is a bug.

**Comment by mpetrun5** [comment]
Partners should just set start block to something custom if they want to skip parsing everything. Honestly, latest flag causes more bugs than it is worth it to have it.
