### ISSUE TITLE
Relayers get stuck in a loop if one network is down

### ISSUE THREAD

**Issue by nmlinaric** [sygmaprotocol/sygma-relayer#162]
Currently if one of the supported networks is down relayers while iterating over chain configs panic and get stuck in a loop.

## Expected Behavior
If relayers can't initialize a connection to one of the networks in the config, they skip it and continue iterating over other networks.

## Current Behavior
Relayers panic is a connection can't be initalized and get stuck in a loop.

## Possible Solution
Replace `panic` with `continue` or some similar error handling that won't get stuck in a loop.

## Steps to Reproduce (for bugs)
Restart relayers while one network in the config is down.

**Comment by itsbobbyzzz168** [comment]
@mpetrun5 also consideration for sygma x relayer (please close this issue if taken care of)

**Comment by mpetrun5** [comment]
I'm still not quite sure what is the correct behavior here.

On one hand we panic and you can't continue, on the other it is best for it to panic so you are notified because often this happens because something is configured wrongly and you'll have adjust the first anyway.

**Comment by mpetrun5** [comment]
We won't do this as if it is stuck the proper way is to remove the network temporarily. This will pose more of a problem if the configuration is invalid and we don't know until it is too late if the network is down.
