### ISSUE TITLE
Merge chainbridge-core into sygma

### ISSUE THREAD

**Issue by P1sar** [sygmaprotocol/sygma-relayer#188]
Currently using chainbridge-core brings a lot of redundancy when updating sygma so it might be a good idea to  merge all core code in to a sygma-relayer
## Implementation details

Merge all core code that used by Sygma in to to sygma-relayer
## Testing details

[] e2e tests
[] unit tests
## Acceptance Criteria

[] no chainbridge-core dependence in sygma-relayer 
[] all tests are passing

**Comment by mpetrun5** [comment]
I will close this for now as we are going to implement `sygma-core` so mostly this doesn't apply anymore.
