### ISSUE TITLE
EVM to Substrate Fungible transfer, not picked by the Relayer on Testnetwork

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-relayer#241]
## Short Context

Using the utils library to trigger a new test coverage for the deployed indexer, a fungible transfer pf PHA token from Goerli to Rhala was not finalized. 

## Preconditions

1. Own a wallet with Gas funds and PHA token on Goerli. (dev wallet: 0x1c3A03D04c026b1f4B4208D2ce053c5686E6FB8d )
2. 

## Steps to Reproduce

1. Execute the transfer route from EVM(Goerli) to Substrate(Rhala) of resource type ID: 0x0000000000000000000000000000000000000000000000000000000000001000 using utils library of a total value of
0.0000005 PHA token (50000000000000000 in 18 dec). 
3.
4.
5.

## Expected Behavior
This transfer should have been complete 
![image](https://github.com/sygmaprotocol/sygma-relayer/assets/30255634/d10f86dc-5831-44ac-9bf6-80f63f3eb320)
https://scan.test.buildwithsygma.com/transfer/0xcc73123ff385452f3d0d081be9e57c8c2d65e84a4e63436d9a5c94bd8def2661

## Actual Behavior
This transaction is still in pending.
![image](https://github.com/sygmaprotocol/sygma-relayer/assets/30255634/0b58c8aa-b09f-4979-a592-0389e20570c1)
https://scan.test.buildwithsygma.com/transfer/0x0f99ef74ee180c3eb7bad76ad2481e33d2dfab0fb71fc1511052a5c7acda9382

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by MakMuftic** [comment]
Resolved in meantime
