### ISSUE TITLE
Add substrate connection

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-relayer#26]
Add substrate connection
## Implementation details
Implement the substrate connection so we are able to fetch data from substrate
implement connection struct with methods:
- GetHeaderLatest() (*types.Header, error)
- GetBlockHash(blockNumber uint64) (types.Hash, error)
- GetBlockEvents(hash types.Hash, target interface{}) error
- UpdateMetatdata() error

## Testing details
add unit tests
## Acceptance Criteria
we are able to establish connection and pull data from substrate chain

**Comment by P1sar** [comment]
Split into Network CLlient implementation and actual Event processing

**Comment by freddyli7** [comment]
after the event fetching and parsing are added, relayer needs to add logic to handle deposit event and retry event
