### ISSUE TITLE
Bad EVM address format on Bitcoin chain deposits, are parsed incorrectly and used on EVM execute proposal

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-relayer#323]
**Context**: Using a bad format for EVM destination address as `0x7FA0A2824EA855EC6aD3eAb3Aa2516EC6626d ` , when depositing on Bitcoin Chain, it is not disregarded by the Relayer. Instead, the address is converted to `0x0007FA0a2824Ea855eC6aD3eAB3aA2516EC6626d` and the proposal is executed, thus living to the lost of user's fund. 

We need to prevent this behavior and not execute on destination is the EVM address format is not valid. 

Deposit on btc: https://blockstream.info/testnet/address/tb1p2q8kwe4efdg7v6glzk97uuzh09fuec4ql2sl68d0c2nyg6kdl2wswannk0 
Output data is here -> 
![image](https://github.com/sygmaprotocol/sygma-relayer/assets/30255634/e058a83c-48e7-4fcc-b932-90519cb0313b)
Deposit picked up by the relayer [here](https://app.datadoghq.com/logs?query=-service%3A%28nginx%20OR%20user-service%20OR%20TESTNET-explorer-indexer%20OR%20ecs-kong-prod%20OR%20pinning-service%20OR%20kong-service%20OR%20go-drand%20OR%20TESTNET-relayers-31%20OR%20TESTNET-relayers-30%20OR%20TESTNET-relayers-2%20OR%20TESTNET-relayers-20%20OR%20TESTNET-relayers-0%20OR%20TESTNET-relayers-1%20OR%20search-service%20OR%20ecs-gaming-api-prod%20OR%20bonds-api%20OR%20MAINNET-rpc-gateway%20OR%20TESTNET-inclusion-prover%20OR%20files-service%20OR%20TESTNET-rpc-gateway%20OR%20TESTNET-spectres-0%20OR%20MAINNET-rebalancing-bot%20OR%20faucet-api%20OR%20TESTNET-gopher-api%20OR%20TESTNET-rebalancing-bot%20OR%20marketplace-api%20OR%20MAINNET-relayers-11%20OR%20MAINNET-relayers-10%20OR%20MAINNET-relayers-21%20OR%20MAINNET-relayers-20%20OR%20MAINNET-relayers-1%20OR%20MAINNET-relayers-0%20OR%20MAINNET-relayers-2%20OR%20MAINNET-relayers-31%20OR%20MAINNET-relayers-30%20OR%20TESTNET-explorer-api%20OR%20ecs-kong-stage%20OR%20MAINNET-explorer-api%20OR%20gaming-api-dd-prod%20OR%20MAINNET-explorer-indexer%20OR%20cleanupbucket%20OR%20pinner-service%20OR%20TESTNET-relayers-40%20OR%20TESTNET-relayers-10%20OR%20billing-service%20OR%20ecs-gaming-api-stage%20OR%20geninvoice-cronjob%20OR%20gaming-api-dd-stage%20OR%20MAINNET-gopher-api%20OR%20gaming%20OR%20storage%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZB4PV5shxgDwQAAAAAAAAAYAAAAAEFaQjRQVjdIQUFDam9ZeUtiR0V0ZUFBQQAAACQAAAAAMDE5MDc4NDItNDQ2YS00OTU3LTk0MDEtZDhiYTlmMzM0N2Ew&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1720003132677&to_ts=1720004032677&live=true)

Execute proposal [here](https://app.datadoghq.com/logs?query=-service%3A%28nginx%20OR%20user-service%20OR%20TESTNET-explorer-indexer%20OR%20ecs-kong-prod%20OR%20pinning-service%20OR%20kong-service%20OR%20go-drand%20OR%20TESTNET-relayers-31%20OR%20TESTNET-relayers-30%20OR%20TESTNET-relayers-2%20OR%20TESTNET-relayers-20%20OR%20TESTNET-relayers-0%20OR%20TESTNET-relayers-1%20OR%20search-service%20OR%20ecs-gaming-api-prod%20OR%20bonds-api%20OR%20MAINNET-rpc-gateway%20OR%20TESTNET-inclusion-prover%20OR%20files-service%20OR%20TESTNET-rpc-gateway%20OR%20TESTNET-spectres-0%20OR%20MAINNET-rebalancing-bot%20OR%20faucet-api%20OR%20TESTNET-gopher-api%20OR%20TESTNET-rebalancing-bot%20OR%20marketplace-api%20OR%20MAINNET-relayers-11%20OR%20MAINNET-relayers-10%20OR%20MAINNET-relayers-21%20OR%20MAINNET-relayers-20%20OR%20MAINNET-relayers-1%20OR%20MAINNET-relayers-0%20OR%20MAINNET-relayers-2%20OR%20MAINNET-relayers-31%20OR%20MAINNET-relayers-30%20OR%20TESTNET-explorer-api%20OR%20ecs-kong-stage%20OR%20MAINNET-explorer-api%20OR%20gaming-api-dd-prod%20OR%20MAINNET-explorer-indexer%20OR%20cleanupbucket%20OR%20pinner-service%20OR%20TESTNET-relayers-40%20OR%20TESTNET-relayers-10%20OR%20billing-service%20OR%20ecs-gaming-api-stage%20OR%20geninvoice-cronjob%20OR%20gaming-api-dd-stage%20OR%20MAINNET-gopher-api%20OR%20gaming%20OR%20storage%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZB4PZyvIiQIygAAAAAAAAAYAAAAAEFaQjRQWjRSQUFEQzVSQ2dTMFpNZXdBQgAAACQAAAAAMDE5MDc4M2QtZGVlYy00NTM1LWE5YWMtZjgxYzhmNjBmYjdj&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1720003132677&to_ts=1720004032677&live=true)

https://sepolia.etherscan.io/tx/0x04167b4ab567784afd05c37ae4026cc0d357fdd9affc668592ba4933107505a2

**Comment by LyonSsS** [comment]
This should be migrated to the SDK logic @MakMuftic 
It seems the older implementation of the relayer works the same. 
There is already an existing issue for this on the SDK https://github.com/sygmaprotocol/sygma-sdk/issues/367 
CC: @mpetrun5

**Comment by mpetrun5** [comment]
Closing as this won't be implemented on relayer.
