### ISSUE TITLE
Failed Execution on BTC is considered resolved if retried from EVM side

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-relayer#325]
**Context**: If an Execution fails on destination side ( BTC) by any reasons, we can execute RETRY from EVM side ( old behavior). 
On this one, the Relayer considers this as an already resolved transaction. 

Deposit: https://sepolia.etherscan.io/tx/0x39c9c4ec59d8b8aa416034c179e0d549b625a651980b65eea57712034684e052 
Retry: https://sepolia.etherscan.io/tx/0x6fcb0dc29febe164013604bd1918e643ec41f14bdab5f037e11ebdc8ecad8182 

Relayer log initial deposit execution [here](https://app.datadoghq.com/logs?query=-service%3A%28nginx%20OR%20user-service%20OR%20TESTNET-explorer-indexer%20OR%20ecs-kong-prod%20OR%20pinning-service%20OR%20kong-service%20OR%20go-drand%20OR%20TESTNET-relayers-31%20OR%20TESTNET-relayers-30%20OR%20TESTNET-relayers-2%20OR%20TESTNET-relayers-20%20OR%20TESTNET-relayers-0%20OR%20TESTNET-relayers-1%20OR%20search-service%20OR%20ecs-gaming-api-prod%20OR%20bonds-api%20OR%20MAINNET-rpc-gateway%20OR%20TESTNET-inclusion-prover%20OR%20files-service%20OR%20TESTNET-rpc-gateway%20OR%20TESTNET-spectres-0%20OR%20MAINNET-rebalancing-bot%20OR%20faucet-api%20OR%20TESTNET-gopher-api%20OR%20TESTNET-rebalancing-bot%20OR%20marketplace-api%20OR%20MAINNET-relayers-11%20OR%20MAINNET-relayers-10%20OR%20MAINNET-relayers-21%20OR%20MAINNET-relayers-20%20OR%20MAINNET-relayers-1%20OR%20MAINNET-relayers-0%20OR%20MAINNET-relayers-2%20OR%20MAINNET-relayers-31%20OR%20MAINNET-relayers-30%20OR%20TESTNET-explorer-api%20OR%20ecs-kong-stage%20OR%20MAINNET-explorer-api%20OR%20gaming-api-dd-prod%20OR%20MAINNET-explorer-indexer%20OR%20cleanupbucket%20OR%20pinner-service%20OR%20TESTNET-relayers-40%20OR%20TESTNET-relayers-10%20OR%20billing-service%20OR%20ecs-gaming-api-stage%20OR%20geninvoice-cronjob%20OR%20gaming-api-dd-stage%20OR%20MAINNET-gopher-api%20OR%20gaming%20OR%20storage%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZB4vaL3Ry7OggAAAAAAAAAYAAAAAEFaQjR2YVpJQUFDdmswSl9zM1NuR0FBRgAAACQAAAAAMDE5MDc4YzQtMjY2Yi00ZGEzLWEzMGEtMmYyYjUyYmQ5N2Qz&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1720007142131&to_ts=1720010742131&live=true)
![image](https://github.com/sygmaprotocol/sygma-relayer/assets/30255634/d5af3ec5-1afd-4c19-b0e8-6375a2106127)

Retry logs [here](https://app.datadoghq.com/logs?query=-service%3A%28nginx%20OR%20user-service%20OR%20TESTNET-explorer-indexer%20OR%20ecs-kong-prod%20OR%20pinning-service%20OR%20kong-service%20OR%20go-drand%20OR%20TESTNET-relayers-31%20OR%20TESTNET-relayers-30%20OR%20TESTNET-relayers-2%20OR%20TESTNET-relayers-20%20OR%20TESTNET-relayers-0%20OR%20TESTNET-relayers-1%20OR%20search-service%20OR%20ecs-gaming-api-prod%20OR%20bonds-api%20OR%20MAINNET-rpc-gateway%20OR%20TESTNET-inclusion-prover%20OR%20files-service%20OR%20TESTNET-rpc-gateway%20OR%20TESTNET-spectres-0%20OR%20MAINNET-rebalancing-bot%20OR%20faucet-api%20OR%20TESTNET-gopher-api%20OR%20TESTNET-rebalancing-bot%20OR%20marketplace-api%20OR%20MAINNET-relayers-11%20OR%20MAINNET-relayers-10%20OR%20MAINNET-relayers-21%20OR%20MAINNET-relayers-20%20OR%20MAINNET-relayers-1%20OR%20MAINNET-relayers-0%20OR%20MAINNET-relayers-2%20OR%20MAINNET-relayers-31%20OR%20MAINNET-relayers-30%20OR%20TESTNET-explorer-api%20OR%20ecs-kong-stage%20OR%20MAINNET-explorer-api%20OR%20gaming-api-dd-prod%20OR%20MAINNET-explorer-indexer%20OR%20cleanupbucket%20OR%20pinner-service%20OR%20TESTNET-relayers-40%20OR%20TESTNET-relayers-10%20OR%20billing-service%20OR%20ecs-gaming-api-stage%20OR%20geninvoice-cronjob%20OR%20gaming-api-dd-stage%20OR%20MAINNET-gopher-api%20OR%20gaming%20OR%20storage%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZB4xYYPTipefgAAAAAAAAAYAAAAAEFaQjR4WW1BQUFCSHBOekRiQnRZQXdBRgAAACQAAAAAMDE5MDc4YzUtYWEyZi00M2IyLWI1ZGItYzBlZjIyNzBlYzAy&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1720007142131&to_ts=1720010742131&live=true)
![image](https://github.com/sygmaprotocol/sygma-relayer/assets/30255634/1e73ef48-b2cd-48c8-a4a7-dded4b1b4c19)

**Comment by mpetrun5** [comment]
There is a PR for this based on audit issues: https://github.com/sygmaprotocol/sygma-relayer/pull/319
Though there are some caveats to it described in the audit issue comments.

**Comment by LyonSsS** [comment]
Going to keep this as cloned issue after https://github.com/sygmaprotocol/sygma-relayer/pull/319 to remind to retest this. 
Thanks for pointing it out @mpetrun5
