### ISSUE TITLE
Handle invalid domains gracefully.

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-relayer#326]
Currently, if you send a deposit from Btc network where there is no contracts and send it to an invalid domain
it will panic and restart the relayer.

## Implementation details

Handle invalid domains gracefully and ignore the deposit.

## Testing details

- unit tests
- manual tests

## Acceptance Criteria

- invalid deposits don't panic the relayer

**Comment by LyonSsS** [comment]
QA tested - 
<img width="1674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXo1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b3e1726a96ca96919d69397873a37ce5b2cc5cd/image.png" alt="image.png" />
https://app.datadoghq.com/logs?query=service%3ADEVNET-relayers-%2A%20-%40domainID%3A%281%20OR%202%20OR%203%29&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Ccontainer_id&event=AgAAAZDZ59mohb4IygAAAAAAAAAYAAAAAEFaRFo1OXVEQUFCZzJLa1JDdy1qSXdBQgAAACQAAAAAMDE5MGQ5ZTctZmUzMy00NWM1LWI1ZDItYWNmYWE5ZGY2ZTkz&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1721208471386&to_ts=1721212071386&live=true
