### ISSUE TITLE
Resource limit exceeded on relayers

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-relayer#47]
## Current Behavior

We realized that our relayers, after working for some time, get to this state where they are not able to open streams toward other relayers (peers).

![image.png](https://images.zenhubusercontent.com/5d89fef759191331a1878a20/c18ca935-92ba-4505-86c3-e0b79f7c1448)

I would say it is related to the connection number limit as described in the discussion below:

[Error on dial: system: cannot reserve connection: resource limit exceeded](https://discuss.libp2p.io/t/error-on-dial-system-cannot-reserve-connection-resource-limit-exceeded/1415)

## Possible Solution

This needs more investigation and generally checking that all connections are being closed once we are not using them anymore. In conjunction with this, I realized that if you observe [the diagram on datadog of memory usage](https://app.datadoghq.com/dashboard/bmh-2cr-2j9/relayersstage?from_ts=1666428768249&to_ts=1669110768249&live=true) for our relayers (check for a month period) we have some kind of memory leakage. This is likely related to connection management.

We first need to validate how connections are being managed by adding some additional logging and then evaluate what is next step.

## Steps to Reproduce (for bugs)

Unfortunately, it is hard to define the exact steps to reproduce this. It happens in our dev environment after relayers work for some time.

**Comment by P1sar** [comment]
I guess first we should add the pprof profiler and include it as part of our monitoring into DataDog. I am not sure how secure to have it always in production. But I guess it would be nice to have it always on. Also, I am not sure does DataDog has memory profile compatible with pprof.
https://go.dev/blog/pprof
https://docs.datadoghq.com/profiler/enabling/go/
