### ISSUE TITLE
Remove startBlock from sharedConfig

### ISSUE THREAD

**Issue by P1sar** [sygmaprotocol/sygma-relayer#96]
keeping startBLock in sharedConfig makes it is impossible to change this value only for one service in order to resync it if necessary. This property should be strictly related only to particular services and should be removed to sharedConfig
## Implementation details

[] Updated shared config specification
[] Make necessary changes for Relayer code
[] Make sure that other services hardly depend on this. If they are crate more issues to handle this

**Comment by mpetrun5** [comment]
Relayers are merging the config so it should overwrite the shared config if it is set in the domain config.
At least it should work like that, I don't know if there is some problem with merging (will check).
